name: Build docker image and Deploy

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set build flag
      run: echo "::set-env name=GIT_TAG::$( git describe --tags --abbrev=0 )"
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kimdictor/web-annie
        tags: ${{env.GIT_TAG}},latest
