name: Release binary
on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - name: Set build flag
      run: |
        echo "::set-env name=GIT_TAG::$( git describe --tags --abbrev=0 )"
        echo "::set-env name=GIT_HASH::$( git rev-parse HEAD )"
        echo "::set-env name=BUILD_DATE::$( date '+%F-%H:%M:%S' )"
    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0
    - uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz"
        binary_name: "web_annie"
        ldflags: |
          -X main.gitTag=${{env.GIT_TAG}}
          -X main.gitHash=${{env.GIT_HASH}}
          -X main.buildDate=${{env.BUILD_DATE}}
        extra_files: static
